on:
    pull_request:
        branches:
            - master
jobs:
    build_cpp:
        name: Build Application
        runs-on: windows-latest
        steps:
            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v1.1

            - name: Build app for release
              run:  ../../FBXWRapperDll/FBXWRapperDll.vcxproj
              #run:  msbuild ..\
              #-t:rebuild -verbosity:diag -property:Configuration=Release                      

              